package db

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5/pgxpool"
)

var Pool *pgxpool.Pool

func InitDB() {
	var err error
	Pool, err = pgxpool.New(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal("Unable to create connection pool:", err)
	}
}

func CloseDB() {
	Pool.Close()
}

func CreateTable() {
	_, err := Pool.Exec(context.Background(), `
	CREATE TABLE IF NOT EXISTS users(
		id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		login         TEXT NOT NULL,
		password_hash TEXT NOT NULL,
		first_name    TEXT,
		last_name     TEXT,
		birthdate     DATE,
		email         TEXT,
		phone_number  TEXT);
	`)

	if err != nil {
		log.Fatal("Error creating a table:", err)
	}
}
