services:
  main-service:
    build: 
      context: main-service
    volumes:
      - ./main-service/signature.pem:/tmp/signature.pem
      - ./main-service/signature.pub:/tmp/signature.pub
    environment:
      JWT_PRIVATE_KEY_FILE: "/tmp/signature.pem"
      JWT_PUBLIC_KEY_FILE: "/tmp/signature.pub"
      DATABASE_URL: "postgresql://postgres:soa@postgres:5432/postgres"
    command: ["--port", "8090"]
    ports:
      - 8090:8090
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: soa
    ports:
      - 5432:5432
    restart: unless-stopped

  tests:
    build:
      context: tests
    environment:
      MAIN_SERVICE_URL: "http://main-service:8090"
      JWT_PRIVATE_KEY_FILE: "/tmp/signature.pem"
      JWT_PUBLIC_KEY_FILE: "/tmp/signature.pub"
    volumes:
      - ./main-service/signature.pem:/tmp/signature.pem
      - ./main-service/signature.pub:/tmp/signature.pub
    depends_on:
      - main-service