services:
  main-service:
    build:
      context: main-service
    volumes:
      - ./main-service/signature/signature.pem:/tmp/signature.pem
      - ./main-service/signature/signature.pub:/tmp/signature.pub
    environment:
      JWT_PRIVATE_KEY_FILE: "/tmp/signature.pem"
      JWT_PUBLIC_KEY_FILE: "/tmp/signature.pub"
      DATABASE_URL: "postgresql://postgres:soa@main-service-db:5432/postgres"
      POST_SERVER_ADDR: "post-service:50051"
      PORT: 8090
    ports:
      - 8090:8090
    depends_on:
      - main-service-db
      - post-service
    restart: unless-stopped
  main-service-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: soa
    restart: unless-stopped
    volumes:
      - main-service-db-data:/var/lib/postgresql/data
  post-service:
    build: 
      context: post-service
    environment:
      DATABASE_URL: "postgresql://postgres:soa@post-service-db:5432/postgres"
      PORT: 50051
    ports:
      - 50051:50051
    depends_on:
      - post-service-db
    restart: unless-stopped
  post-service-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: soa
    restart: unless-stopped
    volumes:
      - post-service-db-data:/var/lib/postgresql/data
  tests:
    build:
      context: tests
    environment:
      MAIN_SERVICE_URL: "http://main-service:8090"
      JWT_PRIVATE_KEY_FILE: "/tmp/signature.pem"
      JWT_PUBLIC_KEY_FILE: "/tmp/signature.pub"
    volumes:
      - ./main-service/signature/signature.pem:/tmp/signature.pem
      - ./main-service/signature/signature.pub:/tmp/signature.pub
    depends_on:
      - main-service
      - post-service
volumes:
  main-service-db-data:
  post-service-db-data: