services:
  main-service:
    build:
      context: main-service
    volumes:
      - ./main-service/signature/signature.pem:/tmp/signature.pem
      - ./main-service/signature/signature.pub:/tmp/signature.pub
    environment:
      JWT_PRIVATE_KEY_FILE: "/tmp/signature.pem"
      JWT_PUBLIC_KEY_FILE: "/tmp/signature.pub"
      DATABASE_URL: "postgresql://postgres:soa@main-service-db:5432/postgres"
      POST_SERVER_ADDR: "post-service:50051"
      KAFKA_URL: "kafka:9092"
      PORT: 8090
    ports:
      - 8090:8090
    depends_on:
      - main-service-db
      - post-service
      - statistic-service
      - kafka
    restart: unless-stopped

  main-service-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: soa
    restart: unless-stopped
    volumes:
      - main-service-db-data:/var/lib/postgresql/data

  post-service:
    build: 
      context: post-service
    environment:
      DATABASE_URL: "postgresql://postgres:soa@post-service-db:5432/postgres"
      PORT: 50051
    ports:
      - 50051:50051
    depends_on:
      - post-service-db
    restart: unless-stopped

  post-service-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: soa
    restart: unless-stopped
    volumes:
      - post-service-db-data:/var/lib/postgresql/data

  statistic-service:
    build: 
      context: statistic-service
    environment:
      DATABASE_URL: "http://statistic-service-db:8123"
      KAFKA_URL: kafka:9092
      PORT: 8100
    depends_on:
      - statistic-service-db
      - kafka
    restart: unless-stopped
    ports:
      - 8100:8100

  statistic-service-db:
    image: yandex/clickhouse-server:latest
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8123:8123

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - 9092:9092

  tests:
    build:
      context: tests
    environment:
      MAIN_SERVICE_URL: "http://main-service:8090"
      JWT_PRIVATE_KEY_FILE: "/tmp/signature.pem"
      JWT_PUBLIC_KEY_FILE: "/tmp/signature.pub"
    volumes:
      - ./main-service/signature/signature.pem:/tmp/signature.pem
      - ./main-service/signature/signature.pub:/tmp/signature.pub
    depends_on:
      - main-service

volumes:
  main-service-db-data:
  post-service-db-data:
  statistic-service-db-data: