package main

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5/pgxpool"
)

type UsersDatabase struct {
	pool *pgxpool.Pool
}

func NewUsersDatabase(databaseUrl string) *UsersDatabase {
	dbpool, err := pgxpool.New(context.Background(), databaseUrl)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Unable to create connection pool:", err)
		os.Exit(1)
	}
	return &UsersDatabase{pool: dbpool}
}

func (db *UsersDatabase) Close() {
	db.pool.Close()
}

func (db *UsersDatabase) CreateTable() error {
	_, err := db.pool.Exec(context.Background(), `
	DROP TABLE IF EXISTS users;

	CREATE TABLE IF NOT EXISTS users(
		id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		login         TEXT NOT NULL,
		password_hash TEXT NOT NULL,
		first_name    TEXT,
		last_name     TEXT,
		birthdate     DATE,
		email         TEXT,
		phone_number  TEXT);
	`)
	return err
}
