// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: protos/statistic_service.proto

package protos

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comparator int32

const (
	Comparator_LIKES Comparator = 0
	Comparator_VIEWS Comparator = 1
)

// Enum value maps for Comparator.
var (
	Comparator_name = map[int32]string{
		0: "LIKES",
		1: "VIEWS",
	}
	Comparator_value = map[string]int32{
		"LIKES": 0,
		"VIEWS": 1,
	}
)

func (x Comparator) Enum() *Comparator {
	p := new(Comparator)
	*p = x
	return p
}

func (x Comparator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Comparator) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_statistic_service_proto_enumTypes[0].Descriptor()
}

func (Comparator) Type() protoreflect.EnumType {
	return &file_protos_statistic_service_proto_enumTypes[0]
}

func (x Comparator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Comparator.Descriptor instead.
func (Comparator) EnumDescriptor() ([]byte, []int) {
	return file_protos_statistic_service_proto_rawDescGZIP(), []int{0}
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostID uint64 `protobuf:"varint,1,opt,name=postID,proto3" json:"postID,omitempty"`
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_statistic_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_statistic_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_protos_statistic_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatisticsRequest) GetPostID() uint64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

type GetTop5PostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comparator Comparator `protobuf:"varint,1,opt,name=comparator,proto3,enum=protos.Comparator" json:"comparator,omitempty"`
}

func (x *GetTop5PostsRequest) Reset() {
	*x = GetTop5PostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_statistic_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTop5PostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTop5PostsRequest) ProtoMessage() {}

func (x *GetTop5PostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_statistic_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTop5PostsRequest.ProtoReflect.Descriptor instead.
func (*GetTop5PostsRequest) Descriptor() ([]byte, []int) {
	return file_protos_statistic_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTop5PostsRequest) GetComparator() Comparator {
	if x != nil {
		return x.Comparator
	}
	return Comparator_LIKES
}

type GetTop5PostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats []*GetTop5PostsResponse_Stat `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
}

func (x *GetTop5PostsResponse) Reset() {
	*x = GetTop5PostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_statistic_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTop5PostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTop5PostsResponse) ProtoMessage() {}

func (x *GetTop5PostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_statistic_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTop5PostsResponse.ProtoReflect.Descriptor instead.
func (*GetTop5PostsResponse) Descriptor() ([]byte, []int) {
	return file_protos_statistic_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTop5PostsResponse) GetStats() []*GetTop5PostsResponse_Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetStatisticsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostID   uint64 `protobuf:"varint,1,opt,name=postID,proto3" json:"postID,omitempty"`
	UserID   uint64 `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	NumLikes uint64 `protobuf:"varint,3,opt,name=numLikes,proto3" json:"numLikes,omitempty"`
	NumViews uint64 `protobuf:"varint,4,opt,name=numViews,proto3" json:"numViews,omitempty"`
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_statistic_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_statistic_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_protos_statistic_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatisticsResponse) GetPostID() uint64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

func (x *GetStatisticsResponse) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetStatisticsResponse) GetNumLikes() uint64 {
	if x != nil {
		return x.NumLikes
	}
	return 0
}

func (x *GetStatisticsResponse) GetNumViews() uint64 {
	if x != nil {
		return x.NumViews
	}
	return 0
}

type GetTop3UsersByLikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats []*GetTop3UsersByLikesResponse_Stat `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
}

func (x *GetTop3UsersByLikesResponse) Reset() {
	*x = GetTop3UsersByLikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_statistic_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTop3UsersByLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTop3UsersByLikesResponse) ProtoMessage() {}

func (x *GetTop3UsersByLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_statistic_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTop3UsersByLikesResponse.ProtoReflect.Descriptor instead.
func (*GetTop3UsersByLikesResponse) Descriptor() ([]byte, []int) {
	return file_protos_statistic_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTop3UsersByLikesResponse) GetStats() []*GetTop3UsersByLikesResponse_Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetTop5PostsResponse_Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostID uint64 `protobuf:"varint,1,opt,name=postID,proto3" json:"postID,omitempty"`
	UserID uint64 `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Num    uint64 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *GetTop5PostsResponse_Stat) Reset() {
	*x = GetTop5PostsResponse_Stat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_statistic_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTop5PostsResponse_Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTop5PostsResponse_Stat) ProtoMessage() {}

func (x *GetTop5PostsResponse_Stat) ProtoReflect() protoreflect.Message {
	mi := &file_protos_statistic_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTop5PostsResponse_Stat.ProtoReflect.Descriptor instead.
func (*GetTop5PostsResponse_Stat) Descriptor() ([]byte, []int) {
	return file_protos_statistic_service_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetTop5PostsResponse_Stat) GetPostID() uint64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

func (x *GetTop5PostsResponse_Stat) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetTop5PostsResponse_Stat) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type GetTop3UsersByLikesResponse_Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   uint64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	NumLikes uint64 `protobuf:"varint,2,opt,name=numLikes,proto3" json:"numLikes,omitempty"`
}

func (x *GetTop3UsersByLikesResponse_Stat) Reset() {
	*x = GetTop3UsersByLikesResponse_Stat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_statistic_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTop3UsersByLikesResponse_Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTop3UsersByLikesResponse_Stat) ProtoMessage() {}

func (x *GetTop3UsersByLikesResponse_Stat) ProtoReflect() protoreflect.Message {
	mi := &file_protos_statistic_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTop3UsersByLikesResponse_Stat.ProtoReflect.Descriptor instead.
func (*GetTop3UsersByLikesResponse_Stat) Descriptor() ([]byte, []int) {
	return file_protos_statistic_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetTop3UsersByLikesResponse_Stat) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetTop3UsersByLikesResponse_Stat) GetNumLikes() uint64 {
	if x != nil {
		return x.NumLikes
	}
	return 0
}

var File_protos_statistic_service_proto protoreflect.FileDescriptor

var file_protos_statistic_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x49, 0x44, 0x22, 0x49, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x35,
	0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0a,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x22, 0x99, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x35, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x35, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x1a, 0x48, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x7f, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x4c, 0x69, 0x6b, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x4c, 0x69, 0x6b, 0x65,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x56, 0x69, 0x65, 0x77, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x56, 0x69, 0x65, 0x77, 0x73, 0x22, 0x99, 0x01,
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x33, 0x55, 0x73, 0x65, 0x72, 0x73, 0x42, 0x79,
	0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x33, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x42, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x1a, 0x3a, 0x0a,
	0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x75, 0x6d, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x6e, 0x75, 0x6d, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x2a, 0x22, 0x0a, 0x0a, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x49, 0x4b, 0x45, 0x53,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x49, 0x45, 0x57, 0x53, 0x10, 0x01, 0x32, 0x85, 0x02,
	0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x35, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x70, 0x35, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x35,
	0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x54, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x33, 0x55, 0x73, 0x65, 0x72, 0x73, 0x42,
	0x79, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x23,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x33, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x42, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_statistic_service_proto_rawDescOnce sync.Once
	file_protos_statistic_service_proto_rawDescData = file_protos_statistic_service_proto_rawDesc
)

func file_protos_statistic_service_proto_rawDescGZIP() []byte {
	file_protos_statistic_service_proto_rawDescOnce.Do(func() {
		file_protos_statistic_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_statistic_service_proto_rawDescData)
	})
	return file_protos_statistic_service_proto_rawDescData
}

var file_protos_statistic_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_statistic_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_statistic_service_proto_goTypes = []interface{}{
	(Comparator)(0),                          // 0: protos.Comparator
	(*GetStatisticsRequest)(nil),             // 1: protos.GetStatisticsRequest
	(*GetTop5PostsRequest)(nil),              // 2: protos.GetTop5PostsRequest
	(*GetTop5PostsResponse)(nil),             // 3: protos.GetTop5PostsResponse
	(*GetStatisticsResponse)(nil),            // 4: protos.GetStatisticsResponse
	(*GetTop3UsersByLikesResponse)(nil),      // 5: protos.GetTop3UsersByLikesResponse
	(*GetTop5PostsResponse_Stat)(nil),        // 6: protos.GetTop5PostsResponse.Stat
	(*GetTop3UsersByLikesResponse_Stat)(nil), // 7: protos.GetTop3UsersByLikesResponse.Stat
	(*empty.Empty)(nil),                      // 8: google.protobuf.Empty
}
var file_protos_statistic_service_proto_depIdxs = []int32{
	0, // 0: protos.GetTop5PostsRequest.comparator:type_name -> protos.Comparator
	6, // 1: protos.GetTop5PostsResponse.stats:type_name -> protos.GetTop5PostsResponse.Stat
	7, // 2: protos.GetTop3UsersByLikesResponse.stats:type_name -> protos.GetTop3UsersByLikesResponse.Stat
	1, // 3: protos.StatisticService.GetStatistics:input_type -> protos.GetStatisticsRequest
	2, // 4: protos.StatisticService.GetTop5Posts:input_type -> protos.GetTop5PostsRequest
	8, // 5: protos.StatisticService.GetTop3UsersByLikes:input_type -> google.protobuf.Empty
	4, // 6: protos.StatisticService.GetStatistics:output_type -> protos.GetStatisticsResponse
	3, // 7: protos.StatisticService.GetTop5Posts:output_type -> protos.GetTop5PostsResponse
	5, // 8: protos.StatisticService.GetTop3UsersByLikes:output_type -> protos.GetTop3UsersByLikesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_statistic_service_proto_init() }
func file_protos_statistic_service_proto_init() {
	if File_protos_statistic_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_statistic_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatisticsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_statistic_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTop5PostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_statistic_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTop5PostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_statistic_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatisticsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_statistic_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTop3UsersByLikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_statistic_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTop5PostsResponse_Stat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_statistic_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTop3UsersByLikesResponse_Stat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_statistic_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_statistic_service_proto_goTypes,
		DependencyIndexes: file_protos_statistic_service_proto_depIdxs,
		EnumInfos:         file_protos_statistic_service_proto_enumTypes,
		MessageInfos:      file_protos_statistic_service_proto_msgTypes,
	}.Build()
	File_protos_statistic_service_proto = out.File
	file_protos_statistic_service_proto_rawDesc = nil
	file_protos_statistic_service_proto_goTypes = nil
	file_protos_statistic_service_proto_depIdxs = nil
}
